<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>Grammar for WebAssembly Text Format</string>
	<key>fileTypes</key>
	<array>
		<string>wat</string>
	</array>
	<key>name</key>
	<string>WebAssembly</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#module</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_line</string>
				</dict>
			</array>
		</dict>
		<key>comment_block</key>
		<dict>
			<key>begin</key>
			<string>\(;</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.begin.wat</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.end.wat</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block.wat</string>
		</dict>
		<key>comment_line</key>
		<dict>
			<key>begin</key>
			<string>;;</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.wat</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.wat</string>
		</dict>
		<key>leading_whitespace</key>
		<dict>
			<key>match</key>
			<string>^\s*</string>
			<key>name</key>
			<string>meta.whitespace.leading</string>
		</dict>
		<key>module</key>
		<dict>
			<key>comment</key>
			<string>the 'value' diagram at http://json.org</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.wat</string>
	<key>uuid</key>
	<string>3CE7870F-287B-4F5E-95BF-305C3D862CD8</string>
</dict>
</plist>
